package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	abilityBlockStart = "<!-- hydra:abilities:start -->"
	abilityBlockEnd   = "<!-- hydra:abilities:end -->"
	routerOwnedMarker = "<!-- generated by hydra: ability router -->"
	abilityIndexFile  = "index.md"
)

func RenderAbilityIndex(abilities []Ability) string {
	var b strings.Builder
	b.WriteString("# Hydra Abilities Index\n\n")
	b.WriteString("<!-- generated by hydra — do not edit -->\n\n")
	b.WriteString("An exact normalized ability-name match is an explicit invocation. Otherwise, choose an ability when its description fits the task. Always read its `ABILITY.md` completely.\n\n")
	if len(abilities) == 0 {
		b.WriteString("No abilities recorded yet.\n")
		return b.String()
	}
	b.WriteString("| Ability | Description | File |\n| --- | --- | --- |\n")
	for _, ability := range abilities {
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",
			ability.Name,
			escapeAbilityCell(ability.Description),
			escapeAbilityCell(filepath.ToSlash(ability.Path)),
		))
	}
	return b.String()
}

func RenderAbilityBlock(s AbilityScope) string {
	index := filepath.ToSlash(filepath.Join(s.AbilitiesDir, abilityIndexFile))
	return fmt.Sprintf(
		"%s\n## Abilities\n\n"+
			"Abilities are reusable workflows. The catalog is kept out of standing context.\n"+
			"Before selecting another workflow, including an agent skill, inspect `%s`. Normalize the\n"+
			"user's requested workflow phrase to lowercase kebab-case. If it exactly matches an ability\n"+
			"name, treat it as an explicit invocation and load that ability first, even when another\n"+
			"available workflow also matches.\n\n"+
			"When no exact name matches, semantic selection is optional. If a task may benefit from an\n"+
			"ability, inspect `%s`, choose semantically,\n"+
			"then read the selected `ABILITY.md` completely before acting. Load referenced files only\n"+
			"as directed by that ability. Hydra does not rank or automatically enforce semantic matches.\n\n"+
			"Use `$ability <name>` for explicit invocation.\n%s\n",
		abilityBlockStart, index, index, abilityBlockEnd,
	)
}

func RenderAbilityRouter(s AbilityScope) string {
	dir := filepath.ToSlash(s.AbilitiesDir)
	index := filepath.ToSlash(filepath.Join(s.AbilitiesDir, abilityIndexFile))
	return fmt.Sprintf(
		"---\nname: ability\n"+
			"description: Load a named Hydra ability when the user invokes $ability <name>.\n---\n\n"+
			"%s\n\n# Hydra ability router\n\n"+
			"Use the first argument as an exact ability name.\n\n"+
			"- If no name was provided, read `%s` and list the available names.\n"+
			"- Accept only lowercase letters, digits, and hyphens. Reject path separators and traversal.\n"+
			"- Resolve the ability to `%s/<name>/ABILITY.md`.\n"+
			"- If that exact file does not exist, read the index and report the available exact names.\n"+
			"- Read the resolved `ABILITY.md` completely before taking task actions.\n"+
			"- Resolve every relative reference from that ability's directory and load supporting files\n"+
			"  only when its instructions require them.\n"+
			"- Follow the ability for the remainder of the task, subject to the user's instructions and\n"+
			"  higher-priority agent instructions.\n",
		routerOwnedMarker, index, dir,
	)
}

func escapeAbilityCell(value string) string {
	return strings.ReplaceAll(value, "|", `\|`)
}
