package main

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	abilityBlockStart = "<!-- hydra:abilities:start -->"
	abilityBlockEnd   = "<!-- hydra:abilities:end -->"
	routerOwnedMarker = "<!-- generated by hydra: ability router -->"
	abilityIndexFile  = "index.md"
	noAbilityTriggers = "—"
)

const abilityMatchContract = "Before selecting any workflow — including an agent skill — check the table below.\n\n" +
	"1. Normalize the user's requested workflow phrase to lowercase kebab-case. If it exactly\n" +
	"   matches an ability name, treat it as an explicit invocation and load that ability\n" +
	"   first, even when another available workflow also matches.\n" +
	"2. Otherwise, if the request *is* one of an ability's Triggers — the whole request, aside\n" +
	"   from case, punctuation, and politeness like \"can you\" or \"please\" — that is an\n" +
	"   explicit invocation too. A trigger that merely appears inside a sentence about other\n" +
	"   work is NOT an invocation: \"ship it\" invokes, \"I need to ship it by Friday\" does not.\n" +
	"3. When several abilities match, they are candidates, not a conflict. Pick the one whose\n" +
	"   description best fits what the user is actually doing, and name the one you picked.\n" +
	"4. Otherwise, choose semantically when an ability's description fits the task.\n\n" +
	"You MUST read the selected `ABILITY.md` completely before acting, and resolve every\n" +
	"relative reference from that ability's directory. Load supporting files only as that\n" +
	"ability directs.\n"

// renderAbilityTable is the catalog shape shared by the external index and the
// in-context block. The block omits the File column: every path is
// <AbilitiesDir>/<name>/ABILITY.md, so repeating it per row buys nothing and
// standing context is the one place that cost recurs on every turn.
func renderAbilityTable(abilities []Ability, withPath bool) string {
	var b strings.Builder
	if withPath {
		b.WriteString("| Ability | Triggers | Description | File |\n| --- | --- | --- | --- |\n")
	} else {
		b.WriteString("| Ability | Triggers | Description |\n| --- | --- | --- |\n")
	}
	for _, ability := range abilities {
		triggers := noAbilityTriggers
		if len(ability.Triggers) > 0 {
			triggers = strings.Join(ability.Triggers, " · ")
		}
		row := fmt.Sprintf("| `%s` | %s | %s |",
			ability.Name,
			escapeAbilityCell(triggers),
			escapeAbilityCell(ability.Description),
		)
		if withPath {
			row += fmt.Sprintf(" %s |", escapeAbilityCell(filepath.ToSlash(ability.Path)))
		}
		b.WriteString(row + "\n")
	}
	return b.String()
}

func RenderAbilityIndex(abilities []Ability) string {
	var b strings.Builder
	b.WriteString("# Hydra Abilities Index\n\n")
	b.WriteString("<!-- generated by hydra — do not edit -->\n\n")
	b.WriteString("An exact normalized ability-name match is an explicit invocation, and so is a trigger match. Otherwise, choose an ability when its description fits the task. Always read its `ABILITY.md` completely.\n\n")
	if len(abilities) == 0 {
		b.WriteString("No abilities recorded yet.\n")
		return b.String()
	}
	b.WriteString(renderAbilityTable(abilities, true))
	return b.String()
}

// RenderAbilityBlock inlines names, triggers, and descriptions the way agent
// skills surface theirs: the cheap metadata has to be in standing context for
// an ability to be selected at all. Only the authored ABILITY.md stays lazy.
func RenderAbilityBlock(s AbilityScope, abilities []Ability) string {
	dir := filepath.ToSlash(s.AbilitiesDir)
	index := filepath.ToSlash(filepath.Join(s.AbilitiesDir, abilityIndexFile))
	var b strings.Builder
	b.WriteString(abilityBlockStart + "\n## Abilities\n\n")
	b.WriteString("Abilities are reusable workflows. Their names, triggers, and descriptions are listed\n" +
		"here; each ability's instructions stay on disk and are read only once it is selected.\n\n")
	b.WriteString(abilityMatchContract)
	b.WriteString("\n")
	if len(abilities) == 0 {
		b.WriteString("No abilities recorded yet. Create one with `hydra ability new <name>`.\n")
	} else {
		b.WriteString(renderAbilityTable(abilities, false))
	}
	b.WriteString(fmt.Sprintf("\nEach ability lives at `%s/<name>/%s`.\n", dir, abilityFilename))
	b.WriteString(fmt.Sprintf("Use `$ability <name>` for explicit invocation. The generated catalog also lives at\n`%s`.\n", index))
	b.WriteString(abilityBlockEnd + "\n")
	return b.String()
}

func RenderAbilityRouter(s AbilityScope) string {
	dir := filepath.ToSlash(s.AbilitiesDir)
	index := filepath.ToSlash(filepath.Join(s.AbilitiesDir, abilityIndexFile))
	return fmt.Sprintf(
		"---\nname: ability\n"+
			"description: Load a named Hydra ability when the user invokes $ability <name>.\n---\n\n"+
			"%s\n\n# Hydra ability router\n\n"+
			"Use the first argument as an exact ability name.\n\n"+
			"- If no name was provided, read `%s` and list the available names.\n"+
			"- Accept only lowercase letters, digits, and hyphens. Reject path separators and traversal.\n"+
			"- Resolve the ability to `%s/<name>/ABILITY.md`.\n"+
			"- If that exact file does not exist, read the index and report the available exact names.\n"+
			"- Read the resolved `ABILITY.md` completely before taking task actions.\n"+
			"- Resolve every relative reference from that ability's directory and load supporting files\n"+
			"  only when its instructions require them.\n"+
			"- Follow the ability for the remainder of the task, subject to the user's instructions and\n"+
			"  higher-priority agent instructions.\n",
		routerOwnedMarker, index, dir,
	)
}

func escapeAbilityCell(value string) string {
	return strings.ReplaceAll(value, "|", `\|`)
}
