package main

import (
	"fmt"
	"strings"
)

const (
	blockStart = "<!-- hydra:rules:start -->"
	blockEnd   = "<!-- hydra:rules:end -->"
)

// RenderIndex produces the canonical index.md: the same table the managed block
// carries, plus a header explaining what the file is.
func RenderIndex(s Scope, rules []Rule) string {
	var b strings.Builder
	b.WriteString("# Hydra Rules Index\n\n")
	b.WriteString("<!-- generated by hydra — do not edit -->\n\n")
	b.WriteString("Find the rows whose trigger or match covers what you are about to do,\n")
	b.WriteString("then read those rule files.\n\n")
	b.WriteString(indexTable(s, rules))
	return b.String()
}

// RenderBlock produces the managed block, sentinels included. Always-rules are
// inlined verbatim; everything else is one table row. Inlining the table (rather
// than pointing at index.md, as Laravel Boost does) means deciding which rules
// apply costs the agent no file reads at all.
func RenderBlock(s Scope, rules []Rule) string {
	var always, indexed []Rule
	for _, r := range rules {
		if r.Always {
			always = append(always, r)
		} else {
			indexed = append(indexed, r)
		}
	}

	var b strings.Builder
	b.WriteString(blockStart + "\n")
	b.WriteString("## Rules\n\n")

	if len(always) > 0 {
		b.WriteString("Always-on rules are inlined below. The rest are lazy-loaded. ")
	}
	b.WriteString("**Before you enter plan mode, run a command, or create/edit a file, you MUST\n")
	b.WriteString("first:** find the index rows whose trigger, glob, or command covers what you are\n")
	b.WriteString("about to do and read those rule files, then run\n")
	b.WriteString(fmt.Sprintf("`grep -rin '<keyword>' %s` to catch what the index alone misses. Do not act\n", s.RulesDirRef()))
	b.WriteString("until you are following every matching rule.\n")

	if !s.Global {
		b.WriteString("\nProject rules override global rules on conflict.\n")
	}

	if len(always) > 0 {
		b.WriteString("\n### Always applies\n")
		for _, r := range always {
			b.WriteString("\n")
			b.WriteString(strings.TrimRight(r.Body, "\n"))
			b.WriteString("\n")
		}
	}

	b.WriteString("\n### Rules index\n\n")
	b.WriteString(indexTable(s, indexed))
	b.WriteString(blockEnd + "\n")
	return b.String()
}

// indexTable renders the matcher table. Always-rules are never listed: their
// bodies are already in the block, so a row would be dead weight.
func indexTable(s Scope, rules []Rule) string {
	var rows []string
	for _, r := range rules {
		if r.Always {
			continue
		}
		rows = append(rows, fmt.Sprintf("| %s | %s | %s |",
			joinPlain(r.Triggers),
			joinCode(append(append([]string{}, r.Paths...), r.Commands...)),
			s.RuleRef(r),
		))
	}
	if len(rows) == 0 {
		return "No rules recorded yet.\n"
	}
	return "| Applies when | Matches (path glob / command) | Rule |\n| --- | --- | --- |\n" +
		strings.Join(rows, "\n") + "\n"
}

// joinPlain joins trigger phrases; a mid-dot separator keeps multi-trigger rows
// readable inside a single table cell.
func joinPlain(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	return strings.Join(items, " · ")
}

// joinCode joins globs and commands, wrapping each in backticks.
func joinCode(items []string) string {
	if len(items) == 0 {
		return "—"
	}
	quoted := make([]string, 0, len(items))
	for _, it := range items {
		quoted = append(quoted, "`"+it+"`")
	}
	return strings.Join(quoted, " · ")
}
